-- MySQL Script generated by MySQL Workbench
-- 2016年05月23日 星期一 09时20分14秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 21pointgame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 21pointgame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `21pointgame` DEFAULT CHARACTER SET utf8 ;
USE `21pointgame` ;

-- -----------------------------------------------------
-- Table `21pointgame`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `21pointgame`.`player` (
  `playerid` INT NOT NULL AUTO_INCREMENT,
  `playername` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) BINARY NOT NULL,
  `roomid` INT NULL,
  `jetton` INT(11) NULL DEFAULT 50,
  `losenum` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`playerid`),
  UNIQUE INDEX `idplayer_UNIQUE` (`playerid` ASC),
  UNIQUE INDEX `playername_UNIQUE` (`playername` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `21pointgame`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `21pointgame`.`room` (
  `roomid` INT NOT NULL AUTO_INCREMENT,
  `player1` VARCHAR(45) NULL,
  `player2` VARCHAR(45) NULL,
  `player3` VARCHAR(45) NULL,
  `player4` VARCHAR(45) NULL,
  `poker` VARCHAR(45) NULL,
  PRIMARY KEY (`roomid`),
  UNIQUE INDEX `roomid_UNIQUE` (`roomid` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
